version: "2"
services:
  redis:
    image: redis:3.0.7
    ports:
      - "6379:6379"
  rebbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"



